name: Greetings on main

on:
  push:
    branches: [develop, main]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for creating the issue, We will be looking into it ASAP"
          pr-message: "Hi Congratulations for your first PR :)"
